<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedidaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table("medidas")->insert([
            [ "codigoClasificador"=> "1","descripcion"=> "BOBINAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "2","descripcion"=> "BALDE","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "3","descripcion"=> "BARRILES","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "4","descripcion"=> "BOLSA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "5","descripcion"=> "BOTELLAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "6","descripcion"=> "CAJA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "7","descripcion"=> "CARTONES","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "8","descripcion"=> "CENTIMETRO CUADRADO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "9","descripcion"=> "CENTIMETRO CUBICO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "10","descripcion"=> "CENTIMETRO LINEAL","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "11","descripcion"=> "CIENTO DE UNIDADES","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "12","descripcion"=> "CILINDRO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "13","descripcion"=> "CONOS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "14","descripcion"=> "DOCENA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "15","descripcion"=> "FARDO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "16","descripcion"=> "GALON INGLES","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "17","descripcion"=> "GRAMO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "18","descripcion"=> "GRUESA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "19","descripcion"=> "HECTOLITRO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "20","descripcion"=> "HOJA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "21","descripcion"=> "JUEGO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "22","descripcion"=> "KILOGRAMO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "23","descripcion"=> "KILOMETRO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "24","descripcion"=> "KILOVATIO HORA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "25","descripcion"=> "KIT","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "26","descripcion"=> "LATAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "27","descripcion"=> "LIBRAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "28","descripcion"=> "LITRO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "29","descripcion"=> "MEGAWATT HORA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "30","descripcion"=> "METRO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "31","descripcion"=> "METRO CUADRADO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "32","descripcion"=> "METRO CUBICO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "33","descripcion"=> "MILIGRAMOS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "34","descripcion"=> "MILILITRO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "35","descripcion"=> "MILIMETRO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "36","descripcion"=> "MILIMETRO CUADRADO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "37","descripcion"=> "MILIMETRO CUBICO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "38","descripcion"=> "MILLARES","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "39","descripcion"=> "MILLON DE UNIDADES","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "40","descripcion"=> "ONZAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "41","descripcion"=> "PALETAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "42","descripcion"=> "PAQUETE","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "43","descripcion"=> "PAR","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "44","descripcion"=> "PIES","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "45","descripcion"=> "PIES CUADRADOS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "46","descripcion"=> "PIES CUBICOS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "47","descripcion"=> "PIEZAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "48","descripcion"=> "PLACAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "49","descripcion"=> "PLIEGO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "50","descripcion"=> "PULGADAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "51","descripcion"=> "RESMA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "52","descripcion"=> "TAMBOR","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "53","descripcion"=> "TONELADA CORTA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "54","descripcion"=> "TONELADA LARGA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "55","descripcion"=> "TONELADAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "56","descripcion"=> "TUBOS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "57","descripcion"=> "UNIDAD (BIENES)","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "58","descripcion"=> "UNIDAD (SERVICIOS)","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "59","descripcion"=> "US GALON (3,7843 L)","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "60","descripcion"=> "YARDA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "61","descripcion"=> "YARDA CUADRADA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "62","descripcion"=> "OTRO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "63","descripcion"=> "ONZA TROY","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "64","descripcion"=> "LIBRA FINA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "65","descripcion"=> "DISPLAY","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "66","descripcion"=> "BULTO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "67","descripcion"=> "DIAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "68","descripcion"=> "MESES","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "69","descripcion"=> "QUINTAL","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "70","descripcion"=> "ROLLO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "71","descripcion"=> "HORAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "72","descripcion"=> "AGUJA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "73","descripcion"=> "AMPOLLA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "74","descripcion"=> "BIDÓN","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "75","descripcion"=> "BOLSA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "76","descripcion"=> "CAPSULA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "77","descripcion"=> "CARTUCHO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "78","descripcion"=> "COMPRIMIDO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "79","descripcion"=> "ESTUCHE","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "80","descripcion"=> "FRASCO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "81","descripcion"=> "JERINGA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "82","descripcion"=> "MINI BOTELLA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "83","descripcion"=> "SACHET","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "84","descripcion"=> "TABLETA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "85","descripcion"=> "TERMO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "86","descripcion"=> "TUBO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "87","descripcion"=> "BARRIL (EEUU) 60 F","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "88","descripcion"=> "BARRIL [42 GALONES(EEUU)]","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "89","descripcion"=> "METRO CUBICO 68F VOL","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "90","descripcion"=> "MIL PIES CUBICOS 14696 PSI","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "91","descripcion"=> "MIL PIES CUBICOS 14696 PSI 68FAH","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "92","descripcion"=> "MILLAR DE PIES CUBICOS (1000 PC)","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "93","descripcion"=> "MILLONES DE PIES CUBICOS (1000000 PC)","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "94","descripcion"=> "MILLONES DE BTU (1000000 BTU)","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "95","descripcion"=> "UNIDAD TERMICA BRITANICA (TI)","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "96","descripcion"=> "POMO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "97","descripcion"=> "VASO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "98","descripcion"=> "TETRAPACK","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "99","descripcion"=> "CARTOLA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "100","descripcion"=> "JABA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "101","descripcion"=> "YARDA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "102","descripcion"=> "BANDEJA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "103","descripcion"=> "TURRIL","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "104","descripcion"=> "BLISTER","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "105","descripcion"=> "TIRA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "106","descripcion"=> "MEGAWATT","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "107","descripcion"=> "KILOWATT","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "108","descripcion"=> "AMORTIZACION","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "109","descripcion"=> "OVULOS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "110","descripcion"=> "SUPOSITORIOS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "111","descripcion"=> "SOBRES","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "112","descripcion"=> "VIAL","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "113","descripcion"=> "HECTAREAS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "114","descripcion"=> "ARROBA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "115","descripcion"=> "AEROSOL","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "116","descripcion"=> "BARRA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "117","descripcion"=> "CONJUNTO","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "118","descripcion"=> "FANEGA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "119","descripcion"=> "PACK","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "120","descripcion"=> "PIPETA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "121","descripcion"=> "POTE","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "122","descripcion"=> "PASTILLA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "123","descripcion"=> "TONELADA METRICA","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],
            [ "codigoClasificador"=> "124","descripcion"=> "EQUIPOS","codigoPuntoVenta"=>0,"codigoSucrsal"=>0],

        ]);
    }
}
