<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TipopagoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table("tipopagos")->insert([
            [ "codigoClasificador"=> "1","descripcion"=> "EFECTIVO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "2","descripcion"=> "TARJETA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "3","descripcion"=> "CHEQUE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "4","descripcion"=> "VALES","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "5","descripcion"=> "OTROS","codigoPuntoVenta "=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "6","descripcion"=> "PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "7","descripcion"=> "TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "8","descripcion"=> "DEPOSITO EN CUENTA - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "9","descripcion"=> "TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "10","descripcion"=> "EFECTIVO-TARJETA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "11","descripcion"=> "EFECTIVO-CHEQUE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "12","descripcion"=> "EFECTIVO-VALES","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "13","descripcion"=> "EFECTIVO - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "14","descripcion"=> "EFECTIVO-DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "15","descripcion"=> "EFECTIVO - TRANSFERENCIA BANCARIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "16","descripcion"=> "TARJETA-CHEQUE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "17","descripcion"=> "TARJETA-VALES","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "18","descripcion"=> "TARJETA-TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "19","descripcion"=> "TARJETA-DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "20","descripcion"=> "TARJETA-TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "21","descripcion"=> "VALES-TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "22","descripcion"=> "VALES - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "23","descripcion"=> "VALES-TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "24","descripcion"=> "TRANSFERENCIA BANCARIA-DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "25","descripcion"=> "TRANSFERENCIA BANCARIA-TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "26","descripcion"=> "DEPOSITO EN CUENTA - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "27","descripcion"=> "GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "30","descripcion"=> "GIFT-CARD OTROS","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "31","descripcion"=> "CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "32","descripcion"=> "BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "33","descripcion"=> "PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "34","descripcion"=> "EFECTIVO - PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "35","descripcion"=> "EFECTIVO - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "36","descripcion"=> "EFECTIVO - CANAL PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "37","descripcion"=> "EFECTIVO - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "38","descripcion"=> "EFECTIVO - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "39","descripcion"=> "TARJETA - PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "40","descripcion"=> "TARJETA - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "41","descripcion"=> "TARJETA - CANAL PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "42","descripcion"=> "TARJETA - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "43","descripcion"=> "TARJETA - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "44","descripcion"=> "CHEQUE - VALES","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "45","descripcion"=> "CHEQUE - PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "46","descripcion"=> "CHEQUE - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "47","descripcion"=> "CHEQUE - DEPOSITO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "48","descripcion"=> "CHEQUE - SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "49","descripcion"=> "CHEQUE - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "50","descripcion"=> "CHEQUE - CANAL PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "51","descripcion"=> "CHEQUE - BILLETERA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "52","descripcion"=> "CHEQUE - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "53","descripcion"=> "VALES - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "54","descripcion"=> "VALES - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "55","descripcion"=> "VALES - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "56","descripcion"=> "VALES - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "57","descripcion"=> "PAGO POSTERIOR - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "58","descripcion"=> "PAGO POSTERIOR - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "59","descripcion"=> "PAGO POSTERIOR - SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "60","descripcion"=> "PAGO POSTERIOR - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "61","descripcion"=> "PAGO POSTERIOR - CANAL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "62","descripcion"=> "PAGO POSTERIOR - BILLETERA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "63","descripcion"=> "PAGO POSTERIOR - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "64","descripcion"=> "TRANSFERENCIA BANCARIA - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "65","descripcion"=> "TRANSFERENCIA BANCARIA - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "66","descripcion"=> "TRANSFERENCIA BANCARIA - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "67","descripcion"=> "TRANSFERENCIA BANCARIA - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "68","descripcion"=> "DEPOSITO EN CUENTA - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "69","descripcion"=> "DEPOSITO EN CUENTA - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "70","descripcion"=> "DEPOSITO EN CUENTA - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "71","descripcion"=> "DEPOSITO EN CUENTA  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "72","descripcion"=> "SWIFT - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "73","descripcion"=> "SWIFT - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "74","descripcion"=> "SWIFT - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "75","descripcion"=> "SWIFT - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "76","descripcion"=> "GIFT-CARD - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "77","descripcion"=> "GIFT-CARD  - BILLETERA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "78","descripcion"=> "GIFT-CARD - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
            [ "codigoClasificador"=> "79","descripcion"=> "CANAL DE PAGO - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "80","descripcion"=> "CANAL DE PAGO - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "81","descripcion"=> "BILLETERA MOVIL - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "82","descripcion"=> "EFECTIVO - TARJETA - PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "83","descripcion"=> "EFECTIVO - TARJETA - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "84","descripcion"=> "EFECTIVO - TARJETA - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "85","descripcion"=> "EFECTIVO - TARJETA - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "86","descripcion"=> "EFECTIVO - TARJETA - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "87","descripcion"=> "EFECTIVO - TARJETA - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "88","descripcion"=> "EFECTIVO - TARJETA - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "89","descripcion"=> "EFECTIVO - TARJETA - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "90","descripcion"=> "EFECTIVO - CHEQUE - PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "91","descripcion"=> "EFECTIVO - CHEQUE - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "92","descripcion"=> "EFECTIVO - CHEQUE - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "93","descripcion"=> "EFECTIVO - CHEQUE - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "94","descripcion"=> "EFECTIVO - CHEQUE - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "95","descripcion"=> "EFECTIVO - CHEQUE - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "96","descripcion"=> "EFECTIVO - CHEQUE - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "97","descripcion"=> "EFECTIVO - CHEQUE - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "98","descripcion"=> "EFECTIVO - VALES - PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "99","descripcion"=> "EFECTIVO - VALES - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "100","descripcion"=> "EFECTIVO - VALES - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "101","descripcion"=> "EFECTIVO - VALES - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "102","descripcion"=> "EFECTIVO - VALES - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "103","descripcion"=> "EFECTIVO - VALES - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "104","descripcion"=> "EFECTIVO - VALES - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "105","descripcion"=> "EFECTIVO - VALES - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "106","descripcion"=> "EFECTIVO - PAGO POSTERIOR - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "107","descripcion"=> "EFECTIVO - PAGO POSTERIOR - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "108","descripcion"=> "EFECTIVO - PAGO POSTERIOR - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "109","descripcion"=> "EFECTIVO - PAGO POSTERIOR - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "110","descripcion"=> "EFECTIVO - PAGO POSTERIOR - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "111","descripcion"=> "EFECTIVO - PAGO POSTERIOR - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "112","descripcion"=> "EFECTIVO - PAGO POSTERIOR - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "113","descripcion"=> "EFECTIVO - TRANSFERENCIA BANCARIA  - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "114","descripcion"=> "EFECTIVO - TRANSFERENCIA BANCARIA  - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "115","descripcion"=> "EFECTIVO - TRANSFERENCIA BANCARIA  - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "116","descripcion"=> "EFECTIVO - TRANSFERENCIA BANCARIA  - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "117","descripcion"=> "EFECTIVO - TRANSFERENCIA BANCARIA  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "118","descripcion"=> "EFECTIVO - TRANSFERENCIA BANCARIA  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "119","descripcion"=> "EFECTIVO - DEPOSITO EN CUENTA  - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "120","descripcion"=> "EFECTIVO - DEPOSITO EN CUENTA  - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "121","descripcion"=> "EFECTIVO - DEPOSITO EN CUENTA  - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "122","descripcion"=> "EFECTIVO - DEPOSITO EN CUENTA  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "123","descripcion"=> "EFECTIVO - DEPOSITO EN CUENTA  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "124","descripcion"=> "EFECTIVO - SWIFT - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "125","descripcion"=> "EFECTIVO - SWIFT - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "126","descripcion"=> "EFECTIVO - SWIFT - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "127","descripcion"=> "EFECTIVO - SWIFT - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "128","descripcion"=> "EFECTIVO - GIFT-CARD - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "129","descripcion"=> "EFECTIVO - GIFT-CARD - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "130","descripcion"=> "EFECTIVO - GIFT-CARD - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "131","descripcion"=> "EFECTIVO - CANAL PAGO - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "132","descripcion"=> "EFECTIVO - CANAL PAGO - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "133","descripcion"=> "EFECTIVO - BILLETERA MOVIL - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "134","descripcion"=> "TARJETA - CHEQUE - PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "135","descripcion"=> "TARJETA - CHEQUE - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "136","descripcion"=> "TARJETA - CHEQUE - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "137","descripcion"=> "TARJETA - CHEQUE - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "138","descripcion"=> "TARJETA - CHEQUE - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "139","descripcion"=> "TARJETA - CHEQUE - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "140","descripcion"=> "TARJETA - CHEQUE - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "141","descripcion"=> "TARJETA - CHEQUE - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "142","descripcion"=> "TARJETA - VALES - PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "143","descripcion"=> "TARJETA - VALES - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "144","descripcion"=> "TARJETA - VALES - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "145","descripcion"=> "TARJETA - VALES - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "146","descripcion"=> "TARJETA - VALES - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "147","descripcion"=> "TARJETA - VALES - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "148","descripcion"=> "TARJETA - VALES - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "149","descripcion"=> "TARJETA - VALES - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "150","descripcion"=> "TARJETA - PAGO POSTERIOR - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "151","descripcion"=> "TARJETA - PAGO POSTERIOR - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "152","descripcion"=> "TARJETA - PAGO POSTERIOR - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "153","descripcion"=> "TARJETA - PAGO POSTERIOR - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "154","descripcion"=> "TARJETA - PAGO POSTERIOR - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "155","descripcion"=> "TARJETA - PAGO POSTERIOR - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "156","descripcion"=> "TARJETA - PAGO POSTERIOR - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "157","descripcion"=> "TARJETA - TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "158","descripcion"=> "TARJETA - TRANSFERENCIA BANCARIA - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "159","descripcion"=> "TARJETA - TRANSFERENCIA BANCARIA - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "160","descripcion"=> "TARJETA - TRANSFERENCIA BANCARIA - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "161","descripcion"=> "TARJETA - TRANSFERENCIA  BANCARIA - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "162","descripcion"=> "TARJETA - TRANSFERENCIA BANCARIA - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "163","descripcion"=> "TARJETA - DEPOSITO EN CUENTA - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "164","descripcion"=> "TARJETA - DEPOSITO EN CUENTA - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "165","descripcion"=> "TARJETA - DEPOSITO EN CUENTA - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "166","descripcion"=> "TARJETA - DEPOSITO EN CUENTA  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "167","descripcion"=> "TARJETA - DEPOSITO EN CUENTA - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "168","descripcion"=> "TARJETA - SWIFT - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "169","descripcion"=> "TARJETA - SWIFT - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "170","descripcion"=> "TARJETA - SWIFT - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "171","descripcion"=> "TARJETA - SWIFT - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "172","descripcion"=> "TARJETA - GIFT-CARD - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "173","descripcion"=> "TARJETA - GIFT-CARD - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "174","descripcion"=> "TARJETA - GIFT-CARD- PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "175","descripcion"=> "TARJETA - CANAL PAGO - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "176","descripcion"=> "TARJETA - CANAL PAGO - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "177","descripcion"=> "TARJETA - BILLETERA MOVIL - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "178","descripcion"=> "CHEQUE - VALES - PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "179","descripcion"=> "CHEQUE - VALES - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "180","descripcion"=> "CHEQUE - VALES - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "181","descripcion"=> "CHEQUE - VALES - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "182","descripcion"=> "CHEQUE - VALES - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "183","descripcion"=> "CHEQUE - VALES - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "184","descripcion"=> "CHEQUE - VALES - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "185","descripcion"=> "CHEQUE - VALES - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "186","descripcion"=> "CHEQUE - PAGO POSTERIOR - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "187","descripcion"=> "CHEQUE - PAGO POSTERIOR - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "188","descripcion"=> "CHEQUE - PAGO POSTERIOR - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "189","descripcion"=> "CHEQUE - PAGO POSTERIOR - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "190","descripcion"=> "CHEQUE - PAGO POSTERIOR - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "191","descripcion"=> "CHEQUE - PAGO POSTERIOR - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "192","descripcion"=> "CHEQUE - PAGO POSTERIOR - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "193","descripcion"=> "CHEQUE - TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "194","descripcion"=> "CHEQUE - TRANSFERENCIA BANCARIA - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "195","descripcion"=> "CHEQUE - TRANSFERENCIA BANCARIA - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "196","descripcion"=> "CHEQUE - TRANSFERENCIA BANCARIA - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "197","descripcion"=> "CHEQUE - TRANSFERENCIA BANCARIA - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "198","descripcion"=> "CHEQUE - TRANSFERENCIA BANCARIA - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "199","descripcion"=> "CHEQUE - DEPOSITO EN CUENTA - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "200","descripcion"=> "CHEQUE - DEPOSITO EN CUENTA - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "201","descripcion"=> "CHEQUE - DEPOSITO EN CUENTA - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "202","descripcion"=> "CHEQUE - DEPOSITO EN CUENTA - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "203","descripcion"=> "CHEQUE - DEPOSITO EN CUENTA - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "204","descripcion"=> "CHEQUE - SWIFT - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "205","descripcion"=> "CHEQUE - SWIFT - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "206","descripcion"=> "CHEQUE - SWIFT - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "207","descripcion"=> "CHEQUE - SWIFT - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "208","descripcion"=> "CHEQUE - GIFT-CARD - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "209","descripcion"=> "CHEQUE - GIFT-CARD - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "210","descripcion"=> "CHEQUE - GIFT-CARD - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "211","descripcion"=> "CHEQUE - CANAL PAGO - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "212","descripcion"=> "CHEQUE - CANAL PAGO - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "213","descripcion"=> "CHEQUE - BILLETERA MOVIL  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "214","descripcion"=> "VALES - SWIFT - TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "215","descripcion"=> "VALES - SWIFT - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "216","descripcion"=> "VALES - SWIFT - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "217","descripcion"=> "VALES - SWIFT - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "218","descripcion"=> "VALES - SWIFT - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "219","descripcion"=> "VALES - SWIFT - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "220","descripcion"=> "VALES - SWIFT - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "221","descripcion"=> "VALES - GIFT-CARD - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "222","descripcion"=> "VALES - GIFT-CARD - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "223","descripcion"=> "VALES - GIFT-CARD - TARJETA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "224","descripcion"=> "VALES - GIFT-CARD - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "225","descripcion"=> "VALES - GIFT-CARD - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "226","descripcion"=> "VALES - GIFT-CARD - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "227","descripcion"=> "VALES - CANAL DE PAGO  - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "228","descripcion"=> "VALES - CANAL DE PAGO  - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "229","descripcion"=> "VALES - CANAL DE PAGO  - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "230","descripcion"=> "VALES - CANAL DE PAGO  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "231","descripcion"=> "VALES - CANAL DE PAGO  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "232","descripcion"=> "VALES - BILLETERA MOVIL - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "233","descripcion"=> "VALES - BILLETERA MOVIL - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "234","descripcion"=> "VALES - BILLETERA MOVIL - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "235","descripcion"=> "VALES - BILLETERA MOVIL - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "236","descripcion"=> "VALES - PAGO ONLINE - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "237","descripcion"=> "VALES - PAGO ONLINE - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "238","descripcion"=> "VALES - PAGO ONLINE - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "239","descripcion"=> "PAGO POSTERIOR - TRANSFERENCIA BANCARIA  - DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "240","descripcion"=> "PAGO POSTERIOR - TRANSFERENCIA BANCARIA  - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "241","descripcion"=> "PAGO POSTERIOR - TRANSFERENCIA BANCARIA  - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "242","descripcion"=> "PAGO POSTERIOR - TRANSFERENCIA BANCARIA  - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "243","descripcion"=> "PAGO POSTERIOR - TRANSFERENCIA BANCARIA  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "244","descripcion"=> "PAGO POSTERIOR - TRANSFERENCIA BANCARIA  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "245","descripcion"=> "PAGO POSTERIOR - DEPOSITO EN CUENTA  - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "246","descripcion"=> "PAGO POSTERIOR - DEPOSITO EN CUENTA  - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "247","descripcion"=> "PAGO POSTERIOR - DEPOSITO EN CUENTA  - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "248","descripcion"=> "PAGO POSTERIOR - DEPOSITO EN CUENTA  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "249","descripcion"=> "PAGO POSTERIOR - DEPOSITO EN CUENTA  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "250","descripcion"=> "PAGO POSTERIOR - SWIFT - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "251","descripcion"=> "PAGO POSTERIOR - SWIFT - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "252","descripcion"=> "PAGO POSTERIOR - SWIFT - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "253","descripcion"=> "PAGO POSTERIOR - SWIFT - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "254","descripcion"=> "PAGO POSTERIOR - GIFT-CARD - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "255","descripcion"=> "PAGO POSTERIOR - GIFT-CARD - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "256","descripcion"=> "PAGO POSTERIOR - GIFT-CARD - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "257","descripcion"=> "PAGO POSTERIOR - CANAL DE PAGO - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "258","descripcion"=> "PAGO POSTERIOR - CANAL DE PAGO - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "259","descripcion"=> "PAGO POSTERIOR - BILLETERA MOVIL - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "260","descripcion"=> "TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA  - TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "261","descripcion"=> "TRANSFERENCIA BANCARIA - DEPOSITO  EN CUENTA - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "262","descripcion"=> "TRANSFERENCIA BANCARIA - DEPOSITO  EN CUENTA - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "263","descripcion"=> "TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA   - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "264","descripcion"=> "TRANSFERENCIA BANCARIA- DEPOSITO  EN CUENTA - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "265","descripcion"=> "TRANSFERENCIA BANCARIA - SWIFT  - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "266","descripcion"=> "TRANSFERENCIA BANCARIA - SWIFT  - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "267","descripcion"=> "TRANSFERENCIA BANCARIA - SWIFT  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "268","descripcion"=> "TRANSFERENCIA BANCARIA - SWIFT  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "269","descripcion"=> "TRANSFERENCIA BANCARIA - GIFT-CARD  - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "270","descripcion"=> "TRANSFERENCIA BANCARIA - GIFT-CARD  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "271","descripcion"=> "TRANSFERENCIA BANCARIA - GIFT-CARD  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "272","descripcion"=> "TRANSFERENCIA BANCARIA - CANAL DE PAGO - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "273","descripcion"=> "TRANSFERENCIA BANCARIA - CANAL DE PAGO - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "274","descripcion"=> "TRANSFERENCIA BANCARIA - BILLETERA MOVIL - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "275","descripcion"=> "DEPOSITO EN CUENTA  - SWIFT  - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "276","descripcion"=> "DEPOSITO EN CUENTA  - SWIFT  - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "277","descripcion"=> "DEPOSITO EN CUENTA  - SWIFT  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "278","descripcion"=> "DEPOSITO EN CUENTA  - SWIFT  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "279","descripcion"=> "DEPOSITO EN CUENTA - GIFT-CARD  - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "280","descripcion"=> "DEPOSITO EN CUENTA - GIFT-CARD  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "281","descripcion"=> "DEPOSITO EN CUENTA  - GIFT-CARD  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "282","descripcion"=> "DEPOSITO EN CUENTA -  CANAL DE PAGO  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "283","descripcion"=> "DEPOSITO EN CUENTA - CANAL DE PAGO   - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "284","descripcion"=> "DEPOSITO EN CUENTA - BILLETERA MOVIL  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "285","descripcion"=> "SWIFT - GIFT-CARD - CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "286","descripcion"=> "SWIFT - GIFT-CARD - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "287","descripcion"=> "SWIFT - GIFT-CARD - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "288","descripcion"=> "SWIFT - CANAL DE PAGO  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "289","descripcion"=> "SWIFT - CANAL  DE PAGO - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "290","descripcion"=> "SWIFT - BILLETERA MOVIL  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "291","descripcion"=> "GIFT-CARD - CANAL DE PAGO  - BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "292","descripcion"=> "GIFT-CARD - CANAL DE PAGO  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "293","descripcion"=> "GIFT-CARD - BILLETERA MOVIL - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "294","descripcion"=> "CANAL DE PAGO - BILLETERA MOVIL  - PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "295","descripcion"=> "DEBITO AUTOMATICO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "296","descripcion"=> "DEBITO AUTOMATICO - EFECTIVO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "297","descripcion"=> "DEBITO AUTOMATICO -TARJETA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "298","descripcion"=> "DEBITO AUTOMATICO - CHEQUE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "299","descripcion"=> "DEBITO AUTOMATICO -  VALE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "300","descripcion"=> "DEBITO AUTOMATICO -  PAGO POSTERIOR","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "301","descripcion"=> "DEBITO AUTOMATICO -  TRANSFERENCIA BANCARIA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "302","descripcion"=> "DEBITO AUTOMATICO -  DEPOSITO EN CUENTA","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "303","descripcion"=> "DEBITO AUTOMATICO -  TRANSFERENCIA SWIFT","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "304","descripcion"=> "DEBITO AUTOMATICO - GIFT-CARD","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "305","descripcion"=> "DEBITO AUTOMATICO -  CANAL DE PAGO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "306","descripcion"=> "DEBITO AUTOMATICO -  BILLETERA MOVIL","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "307","descripcion"=> "DEBITO AUTOMATICO -  PAGO ONLINE","codigoPuntoVenta"=>0,"codigoSucursal"=>0],
             [ "codigoClasificador"=> "308","descripcion"=> "DEBITO AUTOMATICO - OTRO","codigoPuntoVenta"=>0,"codigoSucursal"=>0],

        ]);
    }
}
